image: php:7.2

pipelines:
  branches:
    master:
      - step:
          script:
            - apt-get update && apt-get install -y unzip
            - apt-get -qq install git-ftp curl
            - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://128.65.195.129/web/theatre-la-parenthese/